### ISSUE TITLE
Browservice on startup: closed by remote server

### ISSUE THREAD

**Issue by burritosoftware** [ttalvitie/browservice#10]
Hello, I'm trying to start Browservice whenever my Pi boots. I tried using rc.local and crontab, however they didn't allow Browservice to work, and instead the connection was closed when I try to connect on my Wii.  
  
Is there a preferred way to make this happen?

**Comment by ttalvitie** [comment]
I can't say what is wrong based on this information; what does it mean that Browservice was not allowed to work? Does Browservice even start on boot? Have you tried to forward the standard error stream of Browservice to a file to see if it gives an error message?

One possible way for Browservice to not start correctly during boot is if you bind to a specific network interface by its IP (for example `192.168.1.100`) and the network setup for the interface is not yet complete because the boot is still running. However, this is just guesswork; you have to look at the output to see what is wrong.

There are many perfectly valid ways to start software at boot. In some circumstances I've done this simply by adding a @reboot line to crontab. Systemd services may be useful for example if you need to delay the startup of Browservice until the network has been initialized, though you can usually also achieve this simply by waiting for a few seconds before starting Browservice.

**Comment by burritosoftware** [comment]
I tried to forward the error stream of Browservice to a file, however when I checked it it had nothing in it. I do bind to a specific network interface, so I think I'll need to start it a little bit later. Thank you!
