### ISSUE TITLE
"ERR_SSL_SERVER_CERT_BAD_FORMAT" (self-signed certificate) error while browsing HTTPS sites.

### ISSUE THREAD

**Issue by Nanandmic567** [ttalvitie/browservice#19]
![image](https://user-images.githubusercontent.com/30790322/108933122-2f362800-767d-11eb-92f9-47ed841543a2.png)

As I researched on this error, I found this interesting information..
https://stackoverflow.com/questions/44866244/how-to-reset-ssl-certificate-exceptions-in-chromium/44891000#44891000

_As a side note, its seems that there is an issue currently with Chromium (v58) which seems to be the cause of the chef-server's self-signed certificates coming back with a **ERR_SSL_SERVER_CERT_BAD_FORMAT** error. Both Chrome (v59 on Ubuntu 17.04) and Firefox (v54 on Ubuntu 17.04) are able to read the self-signed certificate as expected and allow traffic to proceed._
(I know it's based on Chromium v88, but it's reference anyways...)

How do I fix this?

**Update:** more references
https://www.magpcss.org/ceforum/viewtopic.php?f=10&t=11068
https://magpcss.org/ceforum/viewtopic.php?f=6&t=10621

**Comment by ttalvitie** [comment]
I cannot reproduce the issue using the same address. Your references seem to all consider the case of self-signed certificates; this should not be relevant for the case of Google, which should have a proper certificate signed by a CA. This issue could be caused by something being wrong with the CA certificates stored on the Linux VM running Browservice, or a man-in-the-middle proxy intercepting all the traffic and using a CA certificate that is not trusted by the Linux VM (or an actual man-in-the-middle attack). You should first check that you can access the HTTPS site at all on the Linux VM, for example by running the command
```
curl https://www.google.co.th/
```
and seeing if you get an SSL error.

**Comment by Nanandmic567** [comment]
OK... So, this is cURL result.

```
HTTP/2 200 
content-type: text/html; charset=windows-874
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Fri, 26 Feb 2021 08:04:17 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Fri, 26 Feb 2021 08:04:17 GMT
cache-control: private
set-cookie: 1P_JAR=2021-02-26-08; expires=Sun, 28-Mar-2021 08:04:17 GMT; path=/; domain=.google.co.th; Secure
set-cookie: NID=210=m7RTaZ9zKkl35wYH2Shl5uq54EPEluFRh_DEWdUTJxBQ9wMU_he4uJuGMDdtn3iIMSDGKOfzx_cJ3WO22fRNl-QIMZSkrdjkgoBbB1r8MTnQclfBSfArAedgBJxmOIEXRT-g4mT2vWOwo-NGRr-0s8i0Rs6HjuRHYTVJp8EYzSk; expires=Sat, 28-Aug-2021 08:04:17 GMT; path=/; domain=.google.co.th; HttpOnly
alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

And yes, I checked on my SparkyLinux VM before (When Browservice isn't running) and it's still access HTTPS sites correctly on any browsers I have installed on, which Browservice don't (except plain HTTP sites that still working).

Furthermore on Browservice where it resulting ERR_SSL_SERVER_CERT_BAD_FORMAT error when accessing HTTPS site, it posting this line...

`[0226/151515.217712:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -167`

Even I tried that with IP binding, still no luck for me....

(Correct me if I'm wrong.)

**Comment by ttalvitie** [comment]
The Browservice HTTP server listen address should not affect this, as the problem occurs with the CEF browser.

Next, it would make sense to see if this problem is specific to Browservice, or if it occurs on other CEF browsers. You can test this by using cefclient (the example program of CEF):

- Install dependencies by running

    ```
    sudo apt install libgtk2.0-dev libgtkglext1-dev
    ```

- Go to the `cef` subdirectory in the Browservice installation and run the following commands to compile cefclient:

    ```
    mkdir build
    cd build
    cmake ..
    make -j3
    ```

- After the compilation has finished, `make` will output a message like `**** Run the following command manually to set SUID permissions ***`. Run the command below it to set the correct permissions for the Chrome sandbox.
- Start CEF client by running

    ```
    tests/cefclient/Release/cefclient
    ```

    A graphical browser window should open. Test whether HTTPS sites work in this browser.

**Comment by Nanandmic567** [comment]
Alright...
And now, even on cefclient ... the CEF browser itself still broken, very very neat.

![cringe](https://user-images.githubusercontent.com/30790322/109372295-6144c580-78db-11eb-8e2a-83263e05a642.jpg)

I'm out of context on this right now.

(P.S. After compiled this, I need to run it as `--no-sandbox` to get it work, otherwise this message will appear in front of me...

`[0227/090016.362054:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/nanandmic567/browservice-0.9.2.0/cef/build/tests/cefclient/Release/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap`)

**Comment by ttalvitie** [comment]
Based on the failure on cefclient, this would seem to be an CEF-wide issue; probably some kind of incompatibility with SparkyLinux. Therefore it is probably outside the scope of Browservice.

Did you run the command below `**** Run the following command manually to set SUID permissions ***` in the `make` output? The error message about SUID sandbox helper would imply that you didn't. However, I think HTTPS should work even with `--no-sandbox`.

**Comment by Nanandmic567** [comment]
Yes I already set that SUID from this properly... And this error slammed me.

(By the way, when I complied Browservice I didn't get this problem when running it with sandbox.)

**Comment by Nanandmic567** [comment]
Update: It's still happened. (Even on Lubuntu, C'mon.)

![image](https://user-images.githubusercontent.com/30790322/109409128-9aa43080-79c2-11eb-93c3-94190c09b712.png)

And also, don't ask about IP binding... It won't work.

So maybe... The CEF v88 build provided by Spotify ... doesn't gonna work for me, unfortunately.

**Comment by ttalvitie** [comment]
This is very odd. I also tested the newest stable SparkyLinux and HTTPS works fine in both Browservice and cefclient. If you get the same issue on cefclient with Lubuntu 18.04, then this is a CEF issue, and you should ask about it on the CEF forums or file a CEF bug.

Since we get different results on cefclient on the same Linux systems, I think the problem has to be about CEF not handling your internet connection or proxy settings correctly. It could also be about locales, though I'm skeptical about it. It's weird that the problem only occurs with CEF, and not other browsers in the Linux VM.

**Comment by Nanandmic567** [comment]
After discussion on other places... I finally did it on Q4OS!!!!
![Squiby did it! Browservice works!!!](https://user-images.githubusercontent.com/30790322/110191604-f1df5080-7e5b-11eb-99e7-2027f1020f3a.png)

And here's the Q4OS' VM...
![This is Q4OS one](https://user-images.githubusercontent.com/30790322/110191665-3f5bbd80-7e5c-11eb-8636-6db6ded8c5d5.png)

So... this should be the finale to the "ERR_SSL_SERVER_CERT_BAD_FORMAT" saga now..
