### ISSUE TITLE
Can custom Cursors CSS on Browservice? but not Work

### ISSUE THREAD

**Issue by JeremyLyokoPPG2020** [ttalvitie/browservice#38]
Add all Type cursors CSS

- This is all Cursors css
<pre>
.alias {cursor: alias;}
.all-scroll {cursor: all-scroll;}
.auto {cursor: auto;}
.cell {cursor: cell;}
.context-menu {cursor: context-menu;}
.col-resize {cursor: col-resize;}
.copy {cursor: copy;}
.crosshair {cursor: crosshair;}
.default {cursor: default;}
.e-resize {cursor: e-resize;}
.ew-resize {cursor: ew-resize;}
.grab {cursor: grab;}
.grabbing {cursor: grabbing;}
.help {cursor: help;}
.move {cursor: move;}
.n-resize {cursor: n-resize;}
.ne-resize {cursor: ne-resize;}
.nesw-resize {cursor: nesw-resize;}
.ns-resize {cursor: ns-resize;}
.nw-resize {cursor: nw-resize;}
.nwse-resize {cursor: nwse-resize;}
.no-drop {cursor: no-drop;}
.none {cursor: none;}
.not-allowed {cursor: not-allowed;}
.pointer {cursor: pointer;}
.progress {cursor: progress;}
.row-resize {cursor: row-resize;}
.s-resize {cursor: s-resize;}
.se-resize {cursor: se-resize;}
.sw-resize {cursor: sw-resize;}
.text {cursor: text;}
.url {cursor: url(myBall.cur),auto;}
.w-resize {cursor: w-resize;}
.wait {cursor: wait;}
.zoom-in {cursor: zoom-in;}
.zoom-out {cursor: zoom-out;}
</pre>

- This Custom Cursors CSS by URL
<pre>
.module {
  cursor: url('path-to-image.png'), auto;	
}
</pre>
Try https://www.cursors-4u.com/ on Browservice but CSS Custom Cursors Not work

**Comment by ttalvitie** [comment]
The set of available cursors is currently limited to the most important ones (normal, link pointer and text selector) due to the limitations in how the server can send signals to the JavaScript client on old browsers (the pointer information has to be sent in the size information of the image; to make this feasible, there should not be too many options). One could implement this by adding a special cursor that would trigger the client to download information about the cursor as another image. However, this is not easy to make portable and risks hurting performance, so I won't be working on this in the near future as priorities are elsewhere (but good pull requests are welcome).

**Comment by achmadsutardi441953** [comment]
Trying CSS Cursor Cur files on Browservice?
.module {
  cursor: url('path-to-image.cur'), auto;	
}
