### ISSUE TITLE
Make Browservice run silent

### ISSUE THREAD

**Issue by vladger** [ttalvitie/browservice#86]
Is there any way to run Browservice silent without visible shell, for example, when you turn on the PC (StartUp)? I tried different shortcut options, no result. "Hidden in tray" shortcut option doesn't help.

**Comment by ttalvitie** [comment]
Currently Browservice is implemented as a console app on Windows as it was the simplest way to port it to Windows; at some point in the future it would probably make it run as a service, so that auto starting and running in the background would be more natural. But for now, let's try to explore some possible solutions for the current console-based Browservice:

I assume that by StartUp you mean the traditional startup folder method for auto-starting programs upon login (i.e., placing shortcuts to the `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` directory). The Windows Task Scheduler is another option for starting programs automatically at boot (it can even startup things before login, but haven't tested whether Browservice can run in a non-graphical environment on Windows, and how it needs to be invoked for that).

The simplest solution is indeed to create a shortcut to `browservice.exe` and place it in the StartUp directory(with the proper command line arguments appended to the target). If I set the shortcut Run property in the Shortcut tab to "Minimized", then it will start minimized, meaning that the window will not be open at boot, but it will be available in the task bar; this could be useful for viewing the log or closing Browservice.
![image](https://user-images.githubusercontent.com/2422716/198880413-2bb38d06-af46-40d9-aa27-a5e1699a26cd.png)

If you really want to hide it from the task bar as well, then the only solution I know is the following:
- Create a text file named `browservice_silent.bat` to the Browservice directory with the following content:
    ```
    browservice.exe 2> browservice.log
    ```
    This batch file will run Browservice and write its log output to `browservice.log`, in case you need to look at it. You may add any command line arguments between `browservice.exe` and `2>`.
- Create a text file named `browservice_silent.vbs` to the Browservice directory with the following content:
    ```
    CreateObject("Wscript.Shell").Run "browservice_silent.bat", 0, True
    ```
    This is a VBScript script that runs the batch file without a visible window (adapted from https://superuser.com/a/390129).
- Create a shortcut to the `browservice_silent.vbs` file and place it in the StartUp directory. On the next login, Browservice should start running completely invisibly in the background. You can read its log output in the `browservice.log` file in the Browservice directory. If you want to stop it from running, you need to end the `browservice.exe` tasks in Task Manager (there are many of them due to the many-process design of Chromium, and it's difficult to find out which one is the main one; you might have to end many of them to get all of them to end).

If you run Browservice hidden in the background, make sure that you don't forget it is running, particularly if you connect the computer to untrusted networks.
